### ISSUE TITLE
Custom yaml variable gives Replacement index 0 out of range for positional args tuple

### ISSUE THREAD

**Issue by jayudhandha** [childsish/dynamic-yaml#20]
Hi,

I am trying to read below SQL queries from yaml file which has 1 dynamic parameter.

`select id from table where name={}`

here **name** will be dynamic and i wanted to apply .format function of python into this string value so that i can change it dynamically.

While reading the key from yaml it gives me below error.

```
File "C:\Users\jayesh\AppData\Local\Programs\Python\Python310\lib\site-packages\dynamic_yaml\yaml_wrappers.py", line 26, in __getitem__
    value = value.format(**super().__getattribute__('_root')._collection)
IndexError: Replacement index 0 out of range for positional args tuple
```

Any help?

Thanks,
Jayesh

**Comment by childsish** [comment]
Dear Jayesh,

Without a minimum reproducible example I can only guess that it's because you haven't included a path to the relevant key between the braces. Please see the README (eg. "`{dirs.home}/venvs/{project_name}`"). If this doesn't help please provide a MRP with the output you expect.

Cheers,
Liam

**Comment by jayudhandha** [comment]
@childsish What you suggested is to use existing properties of yaml.

FYI, I was able to fix by replacing `{}` with `{{}}`.

Now we can read the yaml and apply `.format` on it.

Thanks
