### ISSUE TITLE
How to preserve order when dumping?

### ISSUE THREAD

**Issue by pcotton-intech** [childsish/dynamic-yaml#28]
How to preserve order when dumping?

**Comment by pcotton-intech** [comment]
In the end I just did this. Seems like a fundamental yaml limitation

        
        sections:
           0:
              dothis: "{pipeline.spec}/dothis.yaml"   
           1:
              dothat:
           2:
              pauseandthink:
           3:
              dosomething:
           4:
              finishup:

**Comment by childsish** [comment]
There are two answers to this:
1. By definition, dictionaries are unordered. If you need the entries to be ordered, use a list.
2. It is possible to sort the keys by passing the `sort_keys = True` parameter to the `dump` function.

**Comment by timotheecour** [comment]
but dictionaries are insertion ordered as of Python 3.6. Using a list instead of dict is not a suitable workaround

**Comment by childsish** [comment]
My previous comment was misleading. You can actually provide `sort_keys = False` to the `dump` function preserve the order of keys.

The default behaviour of PyYAML is to sort the keys and there's a long discussion (yaml/pyyaml#110) about whether PyYAML should preserve the order by default or sort the keys and whether preserving the order is backwards compatibility breaking. I agree that preserving the original order is the more intuitive option and after much thinking have decided to make the switch. However, I will consider this to be backwards compatibility breaking and change the major version number to reflect this.

I just hope nobody relies on the keys being sorted on dumping... 😬 If you need your keys to be sorted, please use version 1.3.5 (4499770). Otherwise the brand new 2.0.0 will be for you.
